# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-hello-world-ankit',
                'doc_host': 'https://ankit-thawal47.github.io',
                'git_url': 'https://github.com/ankit-thawal47/nbdev-hello-world-ankit',
                'lib_path': 'nbdev_hello_world_ankit'},
  'syms': {'nbdev_hello_world_ankit.core': {'nbdev_hello_world_ankit.core.foo': ('core.html#foo', 'nbdev_hello_world_ankit/core.py')}}}
